#CI项目
name: IPQ60XX-ALL

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      FIRMWARE_TYPE:
        description: '固件类型'
        required: true
        type: choice
        options:
          - Factory + Sysupgrade
          - uImage Only
        default: 'Factory + Sysupgrade'
      CACHE:
        description: '使用缓存编译'
        default: 'false'
        required: false
        type: boolean
      TEST:
        description: '仅输出配置文件，不编译固件'
        default: 'false'
        required: false
        type: boolean
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。例：CONFIG_PACKAGE_luci-app-homeproxy=y\nCONFIG_PACKAGE_luci-app-openclash=y'
        required: false
        type: string

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES, IPQ60XX-WIFI-NO]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #CPU架构
      CPU_MODEL: arm64
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: ${{ inputs.FIRMWARE_TYPE == 'Factory + Sysupgrade' && 'OWRT' || inputs.FIRMWARE_TYPE == 'uImage Only' && 'RECOVERY' || 'OWRT' }}
      #默认WIFI名称
      WRT_SSID: ${{ inputs.FIRMWARE_TYPE == 'Factory + Sysupgrade' && 'OWRT' || inputs.FIRMWARE_TYPE == 'uImage Only' && 'RECOVERY' || 'OWRT' }}
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: ${{ inputs.FIRMWARE_TYPE == 'Factory + Sysupgrade' && '192.168.10.1' || inputs.FIRMWARE_TYPE == 'uImage Only' && '192.168.1.1' || '192.168.10.1' }}
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #固件类型 - 映射为无空格的内部值
      WRT_FIRMWARE_TYPE: ${{ inputs.FIRMWARE_TYPE == 'Factory + Sysupgrade' && 'factory-sysupgrade' || inputs.FIRMWARE_TYPE == 'uImage Only' && 'uimage-only' || 'factory-sysupgrade' }}
      #使用缓存编译
      WRT_CACHE: ${{inputs.CACHE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
